### ISSUE TITLE
RCPTT tests not working

### ISSUE THREAD

**Issue by ujhelyiz** [FTSRG/EMF-IncQuery-RCPTT-GUI-Tests#3]
After IncQuery version was increased to 1.2, the [UI tests began to fail](https://build.inf.mit.bme.hu/jenkins/job/incquery-rcptt-tests/RCPTT_Results/). Most likely it was caused by an additional dependency on the query explorer introduced in https://bugs.eclipse.org/bugs/show_bug.cgi?id=479311; we should make sure everything works as expected.

@balazsgrill can you have a look?

**Comment by balazsgrill** [comment]
It is caused by the change in QueryExplorer, which involved some changes in the label provider. (it now indicates backend engine). I will update the test cases to reflect the changes.

**Comment by balazsgrill** [comment]
Some of the test cases used mouse events on zest canvas elements. The RCPTT runner failed on these calls with 'unsupported operations'. These lines were removed as they were meaningless in regard to the assertions.
